### PR TITLE
Upgrade to hawkular-parent 30 and the newest Commons and Accounts

### PR DESCRIPTION
**Pull request by ppalaga**
deps

### CODE REVIEW

**Comment by ppalaga** [comment]
@lucasponce 4981600 contains the versions most suitable for WF10 ATM.

**Comment by lucasponce** [comment]
Thx, this Wildfly10 is outdated with master and it has more conflicts, so I have a Wildfly10-II which will be the used for sync with master.
I have an upgrade to parent 10.
I'm going to review the PR and cherry-pick or simply apply missing changes there.

**Comment by ppalaga** [comment]
> I'm going to review the PR and cherry-pick or simply apply missing changes there.

Perfect!

**Comment by lucasponce** [comment]
Applied on Wildfly10-II branch.

**Pull request closed without merging**
